In [1]:
print("Hello Python!")

Hello Python!

In [5]:
import sqlite3
import os
import pandas as pd

# 数据库路径（与 notebook 同目录）
db_path = os.path.join(os.path.dirname("__file__"), "longlist0.db")

# 建立连接
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# 验证连接成功，并查看所有表
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
print(f"✅ 已连接到 {db_path}")
print(f"📋 包含 {len(tables)} 张表：")
for t in tables:
    print(f"   - {t[0]}")

✅ 已连接到 longlist0.db
📋 包含 3 张表：
   - longlist
   - sqlite_stat1
   - sqlite_stat4

In [3]:
# 查询示例
df = pd.read_sql_query("SELECT * FROM longlist LIMIT 10", conn)
df

,isbn,title,author,translator,format,pages,publisher,published,year,votes,rating
0,9788439736967,Boulder,Eva Baltasar,Nicole d'Amonville Alegría,paperback,112,Literatura Random House,2022-08-02,2023,2779,3.77
1,9781628971538,Whale,Cheon Myeong-Kwan,Jae Won Chung,paperback,368,Europa Editions,2023-01-19,2023,175,3.97
2,9781642861181,The Gospel According to the New World,Maryse Condé,Richard Philcox,paperback,184,World Editions,2023-03-07,2023,114,3.05
3,9781529414431,Standing Heavy,Gauz,Frank Wynne,paperback,252,MacLehose Press,2022-05-26,2023,322,3.57
4,9781474623025,Time Shelter,Georgi Gospodinov,Angela Rodel,hardcover,304,W&N,2022-04-21,2023,3142,4.05
5,9781839764318,Is Mother Dead,Vigdis Hjorth,Charlotte Barslund,paperback,330,Verso Fiction,2022-09-27,2023,2455,3.76
6,9781529427820,Jimi Hendrix Live in Lviv,Andrey Kurkov,Reuben Woolley,hardcover,416,MacLehose Press,2023-04-27,2023,167,3.64
7,9781945492655,The Birthday Party,Laurent Mauvignier,Daniel Levin Becker,paperback,454,Transit Books,2023-01-24,2023,529,3.83
8,9781804270288,While We Were Dreaming,Clemens Meyer,Katy Derbyshire,paperback,528,Fitzcarraldo Editions,2023-03-30,2023,705,4.00
9,9781782278627,Pyre,Perumal Murugan,Aniruddhan Vasudevan,paperback,224,Pushkin Press,2022-04-08,2023,1302,4.04

In [6]:
# 数据库适合存储大量结构化数据，尤其是关系型数据。它提供了高效的数据存储和查询能力，支持事务处理和数据完整性约束。
# 数据库优势包括：
# 1. 数据一致性：通过事务和约束，确保数据的完整性和一致性。
# 2. 高效查询：使用索引和优化的查询引擎，能够快速检索大量数据。
# 3. 并发访问：支持多用户同时访问和操作数据，适合团队协作。
# 4. 数据安全：提供权限管理和数据加密，保护敏感信息。
# 5. 可扩展性：适用于从小型应用到大型企业级系统的各种场景。
# CRUD 操作是数据库的基本操作，包括
# 创建（Create）、读取（Read）、更新（Update）和删除（Delete）数据。通过这些操作，用户可以对数据库中的数据进行管理和维护。

# SQL: Structured Query Language（结构化查询语言），是一种用于管理和操作关系型数据库的标准语言。
# SQL 提供了丰富的语法和功能，用于执行数据查询、插入、更新、删除以及数据库结构定义等操作。
# 通过 SQL，用户可以高效地与数据库进行交互，实现数据的存储、检索和分析。

# df = pd.read_sql_query("SELECT * FROM books LIMIT 10", conn)
# df

# SQL是一种声明式语言，用户只需描述想要的数据结果，而不需要指定具体的操作步骤。SQL的核心功能包括：
df = pd.read_sql_query('SELECT title FROM longlist LIMIT 10', conn)
df

df = pd.read_sql_query('SELECT title from longlist LIMIT 5', conn)
df

                                   title
0                                Boulder
1                                  Whale
2  The Gospel According to the New World
3                         Standing Heavy
4                           Time Shelter

In [7]:
df = pd.read_sql_query('SELECT title, author FROM longlist WHERE year = 2023', conn)
df

                                     title              author
0                                  Boulder        Eva Baltasar
1                                    Whale   Cheon Myeong-Kwan
2    The Gospel According to the New World        Maryse Condé
3                           Standing Heavy                Gauz
4                             Time Shelter   Georgi Gospodinov
5                           Is Mother Dead       Vigdis Hjorth
6                Jimi Hendrix Live in Lviv       Andrey Kurkov
7                       The Birthday Party  Laurent Mauvignier
8                   While We Were Dreaming       Clemens Meyer
9                                     Pyre     Perumal Murugan
10                              Still Born    Guadalupe Nettel
11  A System So Magnificent It Is Blinding     Amanda Svensson
12                          Ninth Building         Zou Jingzhi

In [ ]:
# SQL中不等于有两种写法：<> 和 !=，它们的作用相同，都是用于表示不等于的条件。
# 不同数据库系统可能对这两种写法的支持有所不同，但在大多数情况下，它们是可以互换使用的。

df = pd.read_sql_query('SELECT title, format FROM longlist WHERE format != \'Hardcover\'', conn)
df

                                    title     format
0                                 Boulder  paperback
1                                   Whale  paperback
2   The Gospel According to the New World  paperback
3                          Standing Heavy  paperback
4                            Time Shelter  hardcover
..                                    ...        ...
73                         The White Book  paperback
74                      The World Goes On  paperback
75                       Vernon Subutex 1  paperback
76                           Die, My Love  paperback
77                                Flights  paperback

[78 rows x 2 columns]

In [ ]:
# NOT: 用于在 SQL 查询中表示逻辑非操作，通常用于条件表达式中，以排除满足特定条件的记录。

df = pd.read_sql_query('SELECT title, author FROM longlist WHERE NOT format = \'Hardcover\'', conn)
df

                                    title                author
0                                 Boulder          Eva Baltasar
1                                   Whale     Cheon Myeong-Kwan
2   The Gospel According to the New World          Maryse Condé
3                          Standing Heavy                  Gauz
4                            Time Shelter     Georgi Gospodinov
..                                    ...                   ...
73                         The White Book              Han Kang
74                      The World Goes On  László Krasznahorkai
75                       Vernon Subutex 1    Virginie Despentes
76                           Die, My Love        Ariana Harwicz
77                                Flights        Olga Tokarczuk

[78 rows x 2 columns]

In [ ]:
# 逻辑运算符 AND 和 OR 用于在 SQL 查询中组合多个条件，以实现更复杂的筛选逻辑。

df = pd.read_sql_query('SELECT title, author FROM longlist WHERE year = 2022 OR year = 2023', conn)
df

                                     title                   author
0                                  Boulder             Eva Baltasar
1                                    Whale        Cheon Myeong-Kwan
2    The Gospel According to the New World             Maryse Condé
3                           Standing Heavy                     Gauz
4                             Time Shelter        Georgi Gospodinov
5                           Is Mother Dead            Vigdis Hjorth
6                Jimi Hendrix Live in Lviv            Andrey Kurkov
7                       The Birthday Party       Laurent Mauvignier
8                   While We Were Dreaming            Clemens Meyer
9                                     Pyre          Perumal Murugan
10                              Still Born         Guadalupe Nettel
11  A System So Magnificent It Is Blinding          Amanda Svensson
12                          Ninth Building              Zou Jingzhi
13                                Paradais         Fernanda Melchor
14                                  Heaven           Mieko Kawakami
15                    Love in the Big City          Sang Young Park
16                   Happy Stories, Mostly  Norman Erikson Pasaribu
17                             Elena Knows          Claudia Piñeiro
18                      The Book of Mother         Violaine Huisman
19                More Than I Love My Life           David Grossman
20                              Phenotypes              Paulo Scott
21            A New Name: Septology VI-VII                Jon Fosse
22                           After the Sun               Jonas Eika
23                            Tomb of Sand        Geentanjali Shree
24                      The Books of Jacob           Olga Tokarczuk
25                            Cursed Bunny               Bora Chung

In [12]:
df = pd.read_sql_query('SELECT title, author, format FROM longlist WHERE year = 2022 OR year = 2023 AND format = \'Paperback\'', conn)
df

                           title                   author     format
0                       Paradais         Fernanda Melchor  paperback
1                         Heaven           Mieko Kawakami  paperback
2           Love in the Big City          Sang Young Park  paperback
3          Happy Stories, Mostly  Norman Erikson Pasaribu  paperback
4                    Elena Knows          Claudia Piñeiro  paperback
5             The Book of Mother         Violaine Huisman  paperback
6       More Than I Love My Life           David Grossman  paperback
7                     Phenotypes              Paulo Scott  paperback
8   A New Name: Septology VI-VII                Jon Fosse  paperback
9                  After the Sun               Jonas Eika  paperback
10                  Tomb of Sand        Geentanjali Shree  paperback
11            The Books of Jacob           Olga Tokarczuk  paperback
12                  Cursed Bunny               Bora Chung  paperback

In [15]:
# NULL: 用于表示缺失或未知的值。在 SQL 查询中，可以使用 IS NULL 或 IS NOT NULL 来筛选包含或不包含 NULL 值的记录。
df = pd.read_sql_query('SELECT title, author, translator FROM longlist WHERE translator IS NULL', conn)
df

                                     title             author translator
0                         The Perfect Nine  Ngũgĩ wa Thiong'o       None
1  The Enlightenment of The Greengage Tree     Shokoofeh Azar       None

In [16]:
df = pd.read_sql_query('SELECT title, author, translator FROM longlist WHERE translator IS NOT NULL', conn)
df

,title,author,translator
0,Boulder,Eva Baltasar,Nicole d'Amonville Alegría
1,Whale,Cheon Myeong-Kwan,Jae Won Chung
2,The Gospel According to the New World,Maryse Condé,Richard Philcox
3,Standing Heavy,Gauz,Frank Wynne
4,Time Shelter,Georgi Gospodinov,Angela Rodel
...,...,...,...
71,The White Book,Han Kang,Deborah Smith
72,The World Goes On,László Krasznahorkai,"Ottilie Mulzet, George Szirtes, and John Batki"
73,Vernon Subutex 1,Virginie Despentes,Frank Wynne
74,"Die, My Love",Ariana Harwicz,Sarah Moses and Carolina Orloff
75,Flights,Olga Tokarczuk,Jennifer Croft

In [21]:
#LIKE: 用于在 SQL 查询中进行模糊匹配，通常与通配符（如 % 和 _）结合使用，以查找符合特定模式的记录。
# %: 表示任意数量的字符（包括零个字符）。
# _: 表示单个字符。
df = pd.read_sql_query('SELECT title FROM longlist WHERE title LIKE \'%love%\'', conn)
df

                        title
0        Love in the Big City
1    More Than I Love My Life
2  Love in the New Millennium
3                Die, My Love

In [23]:
df = pd.read_sql_query('SELECT title, author FROM longlist WHERE title LIKE \'the %\'', conn)
df

                                      title                   author
0     The Gospel According to the New World             Maryse Condé
1                        The Birthday Party       Laurent Mauvignier
2                        The Book of Mother         Violaine Huisman
3                        The Books of Jacob           Olga Tokarczuk
4                       The War of the Poor            Éric Vuillard
5             The Dangers of Smoking in Bed         Mariana Enríquez
6                             The Employees                Olga Ravn
7                            The Pear Field       Nana Ekvtimishvili
8                          The Perfect Nine        Ngũgĩ wa Thiong'o
9              The Adventures of China Iron  Gabriela Cabezón Cámara
10                The Discomfort of Evening  Marieke Lucas Rijneveld
11                          The Eighth Life       Nino Haratischvili
12  The Enlightenment of The Greengage Tree           Shokoofeh Azar
13                        The Memory Police               Yōko Ogawa
14           The Other Name: Septology I-II                Jon Fosse
15               The Death of Murat Idrissi           Tommy Wieringa
16                    The Faculty of Dreams          Sara Stridsberg
17                         The Pine Islands         Marion Poschmann
18                            The Remainder      Alia Trabucco Zerán
19                   The Shape of the Ruins     Juan Gabriel Vásquez
20                                The Years             Annie Ernaux
21             The 7th Function of Language            Laurent Binet
22                         The Dinner Guest          Gabriela Ybarra
23                      The Flying Mountain       Christoph Ransmayr
24                             The Impostor            Javier Cercas
25                       The Stolen Bicycle               Wu Ming-Yi
26                           The White Book                 Han Kang
27                        The World Goes On     László Krasznahorkai

In [27]:
df = pd.read_sql_query('SELECT title, author FROM longlist WHERE title LIKE \'P_re\'', conn)
df

  title           author
0  Pyre  Perumal Murugan

In [32]:
df = pd.read_sql_query('SELECT title, year FROM longlist WHERE year >= 2020 AND year <= 2022', conn)
# df = pd.read_sql_query('SELECT title, year FROM longlist WHERE year BETWEEN 2020 AND 2022', conn)
df

                                      title  year
0                                  Paradais  2022
1                                    Heaven  2022
2                      Love in the Big City  2022
3                     Happy Stories, Mostly  2022
4                               Elena Knows  2022
5                        The Book of Mother  2022
6                  More Than I Love My Life  2022
7                                Phenotypes  2022
8              A New Name: Septology VI-VII  2022
9                             After the Sun  2022
10                             Tomb of Sand  2022
11                       The Books of Jacob  2022
12                             Cursed Bunny  2022
13                      The War of the Poor  2021
14    When We Cease to Understand the World  2021
15                             Wretchedness  2021
16                   An Inventory of Losses  2021
17              At Night All Blood is Black  2021
18                      I Live in the Slums  2021
19                      In Memory of Memory  2021
20                             Minor Detail  2021
21                           Summer Brother  2021
22            The Dangers of Smoking in Bed  2021
23                            The Employees  2021
24                           The Pear Field  2021
25                         The Perfect Nine  2021
26             The Adventures of China Iron  2020
27                The Discomfort of Evening  2020
28                          The Eighth Life  2020
29  The Enlightenment of The Greengage Tree  2020
30                        The Memory Police  2020
31           The Other Name: Septology I-II  2020
32                                     Tyll  2020
33            Faces on the Tip of My Tongue  2020
34                         Hurricane Season  2020
35                              Little Eyes  2020
36                      Mac and His Problem  2020
37                                  Red Dog  2020
38                                Serotonin  2020

In [33]:
df = pd.read_sql_query('SELECT title, rating FROM longlist WHERE rating BETWEEN 4 AND 5', conn)
df

                                    title  rating
0                            Time Shelter    4.05
1                  While We Were Dreaming    4.00
2                                    Pyre    4.04
3                              Still Born    4.14
4                             Elena Knows    4.10
5                More Than I Love My Life    4.05
6            A New Name: Septology VI-VII    4.50
7                      The Books of Jacob    4.06
8   When We Cease to Understand the World    4.14
9                         The Eighth Life    4.52
10         The Other Name: Septology I-II    4.19
11                       Hurricane Season    4.08
12                              The Years    4.18
13                    The Flying Mountain    4.10

In [37]:
# ASC 和 DESC 是 SQL 中用于指定排序顺序的关键字。ASC 表示升序（从小到大），而 DESC 表示降序（从大到小）。
# 在 ORDER BY 子句中使用这两个关键字，可以对查询结果进行排序。

df = pd.read_sql_query('SELECT title, author, rating, votes FROM longlist ORDER BY rating DESC , votes DESC LIMIT 10', conn)
df

                                   title              author  rating  votes
0                        The Eighth Life  Nino Haratischvili    4.52  16350
1           A New Name: Septology VI-VII           Jon Fosse    4.50    479
2         The Other Name: Septology I-II           Jon Fosse    4.19   1245
3                              The Years        Annie Ernaux    4.18  16888
4  When We Cease to Understand the World   Benajamín Labatut    4.14  23251
5                             Still Born    Guadalupe Nettel    4.14   7647
6                            Elena Knows     Claudia Piñeiro    4.10   8212
7                    The Flying Mountain  Christoph Ransmayr    4.10    323
8                       Hurricane Season    Fernanda Melchor    4.08  22551
9                     The Books of Jacob      Olga Tokarczuk    4.06   5664

In [42]:
df = pd.read_sql_query('SELECT ROUND(AVG(rating), 2) AS average_rating FROM longlist', conn)
df

   average_rating
0            3.75

In [43]:
df = pd.read_sql_query('SELECT MAX(rating) AS highest_rating, MIN(rating) AS lowest_rating FROM longlist', conn)
df

   highest_rating  lowest_rating
0            4.52           3.05

In [45]:
df = pd.read_sql_query('SELECT SUM(votes) AS total_votes FROM longlist', conn)
df

   total_votes
0       604173

In [46]:
df = pd.read_sql_query('SELECT COUNT(*) AS total_books FROM longlist', conn)
df

   total_books
0           78

In [ ]:
# MAX 按照字母顺序比较字符串，返回字母顺序最大的字符串。MIN 按照字母顺序比较字符串，返回字母顺序最小的字符串。

df = pd.read_sql_query('SELECT MAX(title) AS longest_title FROM longlist', conn)
df

  longest_title
0  Wretchedness

In [ ]:
# COUNT(DISTINCT column_name) 用于计算指定列中不同值的数量。它会忽略重复的值，只统计唯一的值，从而得到该列中不同值的总数。

df = pd.read_sql_query('SELECT COUNT(DISTINCT publisher) AS total_publishers FROM longlist', conn)
df

   total_publishers
0                33

In [34]:
cursor.execute("PRAGMA table_info(longlist)")
columns = cursor.fetchall()
for col in columns:
    print(col)

(0, 'isbn', 'TEXT', 0, None, 0)
(1, 'title', 'TEXT', 0, None, 0)
(2, 'author', 'TEXT', 0, None, 0)
(3, 'translator', 'TEXT', 0, None, 0)
(4, 'format', 'TEXT', 0, None, 0)
(5, 'pages', 'INTEGER', 0, None, 0)
(6, 'publisher', 'TEXT', 0, None, 0)
(7, 'published', 'TEXT', 0, None, 0)
(8, 'year', 'INTEGER', 0, None, 0)
(9, 'votes', 'INTEGER', 0, None, 0)
(10, 'rating', 'REAL', 0, None, 0)